### PR TITLE
drop support for win32/osx/hildon, make smclient mandatory

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Did you really mean to drop the dbus backend?

**Comment by monsta** [comment]
Well we can leave it but as I read somewhere it has less features than XSMP one.
It only affects smclient though, so if I'm mistaken here, I can always add it back.

**Comment by monsta** [comment]
@flexiondotorg: actually, [eggsmclient-dbus.c](https://git.gnome.org/browse/libegg/tree/libegg/smclient/eggsmclient-dbus.c) was never here, and was never mentioned in configure.ac. So we're good to go here.

**Comment by infirit** [comment]
merged

**Pull request closed without merging**
