### PR TITLE
avoid deprecated GtkStock

### PR DESCRIPTION
**Pull request by sc0w**
The expected with this PR: the same icons like before

### CODE REVIEW

**Comment by monsta** [comment]
I see that icon is shipped with Atril in `data/icons` directory, it's named `stock_filters-invert`.
See also `libview/ev-stock-icons.c` file.

**Comment by raveit65** [comment]
I can confirm the missing image, but i don't see where it is touched by PR.
```
[rave@mother atril]$ grep -nr EV_STOCK_INVERTED_COLORS *
help/reference/libview/libatrilview-sections.txt:315:EV_STOCK_INVERTED_COLORS
libview/ev-stock-icons.c:49:	{ EV_STOCK_INVERTED_COLORS,  "stock_filters-invert"},
libview/ev-stock-icons.h:48:#define EV_STOCK_INVERTED_COLORS        "inverted"
shell/ev-window.c:6424:	{ "ViewInvertedColors", EV_STOCK_INVERTED_COLORS, N_("_Inverted Colors"), "<control>I",
[rave@mother atril]$ grep -nr stock_filters-invert *
data/icons/24x24/actions/Makefile.am:8:	stock_filters-invert.png	\
libview/ev-stock-icons.c:49:	{ EV_STOCK_INVERTED_COLORS,  "stock_filters-invert"},
```

**Comment by raveit65** [comment]
And the icon is installed here.
```
[root@mother rave]# ls -l /usr/share/atril/icons/hicolor/24x24/actions/insgesamt 32
-rw-r--r-- 1 root root  924 15. Feb 10:26 object-rotate-left.png
-rw-r--r-- 1 root root  943 15. Feb 10:26 object-rotate-right.png
-rw-r--r-- 1 root root  402 15. Feb 10:26 stock_filters-invert.png
-rw-r--r-- 1 root root  724 15. Feb 10:26 view-page-continuous.png
-rw-r--r-- 1 root root  471 15. Feb 10:26 view-page-facing.png
-rw-r--r-- 1 root root 1146 15. Feb 10:26 zoom-fit-height.png
-rw-r--r-- 1 root root 1170 15. Feb 10:26 zoom-fit-width.png
-rw-r--r-- 1 root root 1344 15. Feb 10:26 zoom.png
```

**Comment by raveit65** [comment]
Ok, if i don't use this part of the Pr than the icon is there.
```
diff --git a/cut-n-paste/toolbar-editor/egg-toolbar-editor.c b/cut-n-paste/toolbar-editor/egg-toolbar-editor.c
index f9e3f22..a52255b 100644
--- a/cut-n-paste/toolbar-editor/egg-toolbar-editor.c
+++ b/cut-n-paste/toolbar-editor/egg-toolbar-editor.c
@@ -509,8 +509,8 @@ editor_create_item_from_name (EggToolbarEditor *editor,
         icon = gtk_image_new_from_icon_name (icon_name,
 	                                     GTK_ICON_SIZE_LARGE_TOOLBAR);
       else
-        icon = gtk_image_new_from_stock (stock_id ? stock_id : GTK_STOCK_DND,
-                                         GTK_ICON_SIZE_LARGE_TOOLBAR);
+        icon = gtk_image_new_from_icon_name (stock_id ? stock_id : "gtk-dnd",
+                                             GTK_ICON_SIZE_LARGE_TOOLBAR);
 
       item_name = g_strdup (name);
       collate_key = g_utf8_collate_key (short_label, -1);
```
Interesting is the comment.
```
      /* This is a workaround to catch named icons. */
      if (icon_name)
        icon = gtk_image_new_from_icon_name (icon_name,
	                                     GTK_ICON_SIZE_LARGE_TOOLBAR);
      else
        icon = gtk_image_new_from_icon_name (stock_id ? stock_id : "gtk-dnd",
                                             GTK_ICON_SIZE_LARGE_TOOLBAR);
```

**Comment by sc0w** [comment]
@raveit65 yes, that line is the problem

Fixed

I will do the same for eom, it has the same code

please test again

**Comment by lukefromdc** [comment]
Does https://github.com/mate-desktop/marco/pull/387#issuecomment-365918509
apply to these changes too?  I see ""use-stock", TRUE," in the code here too

**Comment by sc0w** [comment]
@lukefromdc 

I am reviewing older PRs merged, this is pending

**Comment by sc0w** [comment]
ok, now I hope all is fine

please test and review

**Comment by lukefromdc** [comment]
This latest change works, and the "Inverted Colors" icon appears just fine

**Comment by raveit65** [comment]
This works but at least this needs some work for gtk+-4, see 'storage-type for the 'inverted' icon.
atril-gtkstock
Anyway, thanks for your hard work for reducing build warnings.

**Comment by sc0w** [comment]
@raveit65 ok, nice catch!

a lot of work is pending for gtk4

**Comment by sc0w** [comment]
@raveit65 are you sure?

I think you are wrong

with this PR merged, with git master, I see in the inverted icon properties:

inverted_properties

**Comment by raveit65** [comment]
You're right , i used wrong patch for building.
Storage type is GTK_IMAGE_ICON_NAME now.
Sorry, for that noise.

**Pull request merged**
