### PR TITLE
Fix for #365 ("Odd Pages Left" accelerator).

### PR DESCRIPTION
**Pull request by apalsson**
As requested in #365 to add accelerator for "Odd Pages Left" in dual page mode.
The character "o" was chosen as suggested, no other accelerator is bound to that character.

### CODE REVIEW

**Comment by vkareh** [comment]
@apalsson - What @raveit65 meant was to change your actual commit message... Something like "Added accelerator 'o' for toggling Odd Pages Left"

**Comment by raveit65** [comment]
Something like this:
```
Added accelerator 'o' for toggling Odd Pages Left

fixes https://github.com/mate-desktop/atril/issues/365
```

**Comment by apalsson** [comment]
@raveit65 @vkareh apologies for the misunderstanding, I first believe there was links as GitHub created the automatically.

**Comment by raveit65** [comment]
Thanks.

**Pull request merged**
