### PR TITLE
Fix segfault on empty navMap

### PR DESCRIPTION
**Pull request by errt**
Port of https://github.com/linuxmint/xreader/pull/334 to fix https://github.com/linuxmint/xreader/issues/274 that also affects atril.

### CODE REVIEW

**Comment by raveit65** [comment]
Example document for reproducing the crash, please?

**Comment by raveit65** [comment]
@errt 
Example document for reproducing the crash, please?

**Comment by raveit65** [comment]
@errt 
We can't add code when author doesn't answer.
...but we can close.

**Comment by errt** [comment]
Sorry, I'm not a user of atril, but of xreader and only reported this here, too, as it uses the same code base. As xreader has merged the proposed fix, I did not keep track of this anymore. I don't think I have a document at hand that triggers the reported behavior and I'm not sure I could craft a minimal example. As I personally don't care that much about atril and this is not a major bug, feel free to close it if you want to. On the other hand, I don't see much harm in the proposed change, it just ensures that no error can occur if a document, in violation of the standard, has an empty navMap. Your choice whether you consider this useful or not.

**Comment by raveit65** [comment]
@errt 
I asked several times for a example document to reproduce the issue. Can you provide one?
I do not have such a document for myself.

**Comment by rbuj** [comment]
Test document: guide2.epub (without navMap) and guide2.epub (with navMap)
```
wget http://www.ibiblio.org/pub/Linux/docs/LDP/users-guide/user-beta-1-src.tar.gz
tar xzvf user-beta-1-src.tar.gz 
cd user
pandoc -s guide.tex -o guide.epub
mkdir -p epub
unzip guide.epub -d epub
```
delete navMap:
```
$ grep -nR navMap
epub/EPUB/toc.ncx:12:  <navMap>
epub/EPUB/toc.ncx:1117:  </navMap>
$ sed -i 12,1117d epub/EPUB/toc.ncx
```
compress:
```
$ (cd epub && zip -rX ../guide2.epub  mimetype META-INF EPUB)
$ gzip guide2.epub 
$ gzip guide.epub
```
[guide.epub.gz](https://github.com/mate-desktop/atril/files/4902573/guide.epub.gz)
[guide2.epub.gz](https://github.com/mate-desktop/atril/files/4902575/guide2.epub.gz)

**Comment by errt** [comment]
The missing navMap may be a different, but possibly related issue.
An empty navMap crashes atril 1.24 here, but does not crash xreader 2.6.4. Maybe a change since atril 1.24 already mitigated the issue.

**Pull request merged**
