### PR TITLE
Remove compilation warnings and set 'always_show_image' Properties in the UI file

### PR DESCRIPTION
**Pull request by zhuyaliang**

### CODE REVIEW

**Comment by raveit65** [comment]
Commit works fine. I think you can delete double `data/atril-toolbar.xml` and `data/atril-ui.xml`.
They are already /shell dir and not in extradist of /data dir.
So they was never in released tarball and would use for building.

**Review by lukefromdc — APPROVED** [review]
This suppressed 4 build warnings with my normal build options (there are many others at this time). The build finished with no issues and runtime behavior was same as before

**Comment by zhuyaliang** [comment]
If that's the case, we can delete this file in the next submission

**Comment by raveit65** [comment]
> If that's the case, we can delete this file in the next submission

Good, i have already a commit prepared for this.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
