### PR TITLE
Bump synctex to 1.21

### PR DESCRIPTION
**Pull request by rbuj**
```
$ cd cut-n-paste/synctex
$ rm synctex_*
$ ./update-synctex-from-TL.sh
```

Test on Fedora:

  1. Install required packages
```
$ sudo dnf install texlive-scheme-basic texlive-lipsum -y
```
  2. Build a pdf with synctex enabled
```
$ cat <<EOF >> file.tex
\documentclass[12pt]{report}
\usepackage{lipsum}
\begin{document}
\chapter{Introduction}
\lipsum[2-4]
\end{document}
EOF
$ pdflatex -synctex=1 file.tex
```
   3. Open file.pdf using atril
   4. Search any text string

### CODE REVIEW

**Comment by sc0w** [comment]
it seems to be more efficient the code seeing the website reports:

clang warnings: master: 286,  this PR: 220
cppcheck warnings: master 305, this PR: 236

**Comment by sc0w** [comment]
new warnings detected in this PR:

```
synctex_parser.c: In function 'synctex_reader_init_with_output_file':
synctex_parser.c:750:9: warning: label 'bailey' defined but not used [-Wunused-label]
  750 |         bailey:
      |         ^~~~~~

synctex_parser.c: In function '__synctex_parse_sfi':
synctex_parser.c:5455:9: warning: label 'continue_scan' defined but not used [-Wunused-label]
 5455 |         continue_scan:
      |         ^~~~~~~~~~~~~

synctex_parser.c: In function '_synctex_updater_print_gz':
synctex_parser.c:8450:13: warning: implicit declaration of function 'vasprintf'; did you mean 'vsprintf'? [-Wimplicit-function-declaration]
 8450 |         if (vasprintf(&buffer, format, va) < 0) {
      |             ^~~~~~~~~

synctex_parser.c:441:1: warning: Access to field 'class_' results in a dereference of a null pointer (loaded from variable 'node')
DEFINE_SYNCTEX_TREE__GETSETRESET(sibling)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

synctex_parser.c:415:51: note: expanded from macro 'DEFINE_SYNCTEX_TREE__GETSETRESET'
#   define DEFINE_SYNCTEX_TREE__GETSETRESET(WHAT) \
                                                  ^

synctex_parser.c:381:23: note: expanded from macro '\
DEFINE_SYNCTEX_TREE__GET'
    return node->data[node->class_->navigator->WHAT].as_node;\
                      ^~~~~~~~~~~~

synctex_parser.c:3928:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4042:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4073:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0, 0};
                 ^~   ~~~~~~

synctex_parser.c:4145:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4155:35: warning: Potential leak of memory pointed to by 'string'
            return (synctex_ss_s){NULL,zs.status};
                                  ^~~~

synctex_parser.c:4210:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4288:18: warning: Value stored to 'is' during its initialization is never read
    synctex_is_s is = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4289:18: warning: Value stored to 'ss' during its initialization is never read
    synctex_ss_s ss = {NULL,0};
                 ^~   ~~~~~~~~

synctex_parser.c:4322:16: warning: Potential memory leak
        return status;
               ^~~~~~

synctex_parser.c:4371:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4451:18: warning: Value stored to 'fs' during its initialization is never read
    synctex_fs_s fs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:4542:18: warning: Value stored to 'is' during its initialization is never read
    synctex_is_s is = {0,0};
                 ^~   ~~~~~

synctex_parser.c:5046:18: warning: Value stored to 'zs' during its initialization is never read
    synctex_zs_s zs = {0,0};
                 ^~   ~~~~~

synctex_parser.c:5066:18: warning: Value stored to 'ns' during its initialization is never read
    synctex_ns_s ns = SYNCTEX_NS_NULL;
                 ^~   ~~~~~~~~~~~~~~~

synctex_parser.c:5077:5: warning: Value stored to 'status' is never read
    status = SYNCTEX_STATUS_OK;
    ^        ~~~~~~~~~~~~~~~~~

synctex_parser.c:5177:5: warning: Value stored to 'ns' is never read
    ns = SYNCTEX_NS_NULL;
    ^    ~~~~~~~~~~~~~~~

synctex_parser.c:5214:5: warning: Value stored to 'ns' is never read
    ns = SYNCTEX_NS_NULL;
    ^    ~~~~~~~~~~~~~~~

synctex_parser.c:5369:25: warning: Value stored to 'child' is never read
                        child = sibling;
                        ^       ~~~~~~~

synctex_parser.c:5857:18: warning: Value stored to 'ns' during its initialization is never read
    synctex_ns_s ns = {NULL,SYNCTEX_STATUS_NOT_OK};
                 ^~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

synctex_parser.c:7551:27: warning: Use of memory after it is freed
        scanner->iterator = synctex_iterator_new_display(scanner, name,line,column, page_hint);
        ~~~~~~~~~~~~~~~~~ ^

synctex_parser.c:7559:27: warning: Use of memory after it is freed
        scanner->iterator = synctex_iterator_new_edit(scanner, page, h, v);
        ~~~~~~~~~~~~~~~~~ ^

synctex_parser.c:8114:22: warning: Value stored to 'nd' during its initialization is never read
        synctex_nd_s nd = SYNCTEX_ND_0;
                     ^~   ~~~~~~~~~~~~

synctex_parser.c:8314:26: warning: Value stored to 'nd' during its initialization is never read
            synctex_nd_s nd = SYNCTEX_ND_0;
                         ^~   ~~~~~~~~~~~~

synctex_parser.c:8348:18: warning: Value stored to 'nd' during its initialization is never read
    synctex_nd_s nd = SYNCTEX_ND_0;
                 ^~   ~~~~~~~~~~~~
```

**Comment by yetist** [comment]
Is it possible to compile with the synctex library that comes from the distro?

**Comment by raveit65** [comment]
> Is it possible to compile with the synctex library that comes from the distro?

yes, we this evince commit
https://gitlab.gnome.org/GNOME/evince/commit/9edaca5b7b35bbbeeecfaf8d9291a4c092d8be91
and probably more
https://gitlab.gnome.org/GNOME/evince/commits/master?utf8=%E2%9C%93&search=synctex

**Comment by rbuj** [comment]
libsynctex is providd by texlive-lib-devel on Fedora:
```
$ rpm -qf /usr/lib64/libsynctex.so
texlive-lib-devel-20180414-35.fc30.x86_64
```

**Comment by sc0w** [comment]
@mate-desktop/core-team what do you think about removing all the synctex code, less code to maintain... and keep it as dependency?

**Comment by lukefromdc** [comment]
From what I saw of the test instructions I doubt I've ever used it but be advised
my usage is rather basic when it comes to PDFs. Question is this: will removing
it lead to any PDF files.someone may have that opens in Atril now no longer being
readable? If not this might be expendable. Be advised however I know little about it.

**Comment by monsta** [comment]
Evince still keeps internal synctex for some reason... maybe not all the distros have it packaged?

**Comment by raveit65** [comment]
I don't mind, at least it wasn't much work to use internal SyncTeX the last years. Only updating from time to time.

@rbuj 
Not related to your work here, any chance to fix that build warning which is in master, please?
Than SyncTeX part is done.
```
Making all in synctex
make[3]: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/atril-dist/cut-n-paste/synctex'
  CC       libsynctex_la-synctex_parser.lo
  CC       libsynctex_la-synctex_parser_utils.lo
synctex_parser_utils.c: In function '_synctex_merge_strings':
synctex_parser_utils.c:322:17: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  322 |      if(dest != strncpy(dest,temp,size)) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
synctex_parser_utils.c:320:16: note: length computed here
  320 |     if((size = strlen(temp))>0) {
      |                ^~~~~~~~~~~~
synctex_parser_utils.c: In function '_synctex_get_name':
synctex_parser_utils.c:402:20: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  402 |     if(dir_name != strncpy(dir_name,output,size)) {
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
synctex_parser_utils.c:393:11: note: length computed here
  393 |    size = strlen(output)-strlen(base_name);
      |           ^~~~~~~~~~~~~~
  CCLD     libsynctex.la
```

**Comment by rbuj** [comment]
@raveit65 - At first sight, `_synctex_merge_strings` looks like [g_strconcat](https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strconcat)

**Comment by raveit65** [comment]
Let's handle all suggestions later in different PRs if someone is interested.

**Pull request merged**
