### PR TITLE
Clang analyzer

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by raveit65** [comment]
I just enabled gh-pages.

**Comment by yetist** [comment]
ok, too many bugs, wating for the ssl certificates.

**Comment by raveit65** [comment]
Looks, like ssl certificates aren't there after a day and firefox warns me.
```
Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to atril.mate-desktop.dev because this website requires a secure connection.

What can you do about it?

atril.mate-desktop.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.
```

**Comment by yetist** [comment]
It is OK now, https://atril.mate-desktop.dev/

**Pull request merged**
