### PR TITLE
shell: Respect user's toolbar-style setting

### PR DESCRIPTION
**Pull request by zeldin**
Atril should respect if the user wants another toolbar-style than "both-horiz" by checking the "toolbar-style" key of the "org.mate.interface" schema in GSettings.

### CODE REVIEW

**Comment by monsta** [comment]
Nice - but would be better to check the existence of the schema before using it. There are people who use Atril in other desktop environments.

Also this setting is completely ignored in GTK+3 build - they made it no-op at some point... IIRC it was in GTK+ 3.10.

**Comment by zeldin** [comment]
Right you are.  I run it in XFCE myself, but I still have all the MATE schemas installed.  :smile:
I pushed a fix to this PR.

> Also this setting is completely ignored in GTK+3 build

Hm?  The patch works fine for me (as in, all the styles do what they are supposed to when I set the setting) with GTK+3.20.6 on Debian stretch...

**Comment by monsta** [comment]
I recall eom ignores this setting in GTK+3 build, so I thought Atril does the same... I'll check it once more.

**Comment by monsta** [comment]
Hmm, interesting... GTK+2 build of Atril reacts to this setting even without this PR. The only issue is that "icon" value isn't processed properly - Atril uses "both" value instead. GTK+2 build of eom has the same behavior. I'll check GTK+3 build later.

**Comment by raveit65** [comment]
@monsta 
What is the state of merging this PR?
Or do we need this with gtk3 build any more?

**Comment by monsta** [comment]
Ok, it works with current git master. I guess it's because we have a custom "libegg" toolbar, not some standard GTK+ one. I remember the toolbars settings were ignored in the standard one, therefore we removed them from the last tab of mate-appearance-properties...

**Comment by monsta** [comment]
> GTK+2 build of Atril reacts to this setting even without this PR. The only issue is that "icon" value isn't processed properly - Atril uses "both" value instead. 

Here in GTK+3 code we get the same behavior with this PR. In other words, it seems ok since it restores the old behavior. As for some values not working, I guess it's some separate issue in the toolbars.

**Comment by raveit65** [comment]
hmm, it seems to be a bit inconsistent.
- both --> text is under icons on most buttons
- icon --> i see only icons, but for forward/previous buttons i see icons and text.
- both-horz --> same as with icons

**Comment by monsta** [comment]
Yes, this inconsistency is what I was talking about. You can check GTK+2 build and see it there as well. That's why I think it's some separate issue in the toolbars.

**Comment by raveit65** [comment]
As, this doesn't work for normal Gtk Toolbars i am in doubt that i will ever use that ;-)
I don't like to use all the old deprecated gtk+2 stuff for myself........
So feel free to merge it if you think it is OK.

**Comment by monsta** [comment]
Ok, rebased and merged.

**Pull request merged**
