### PR TITLE
Update Catalan translation of manual

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Translations will be done by transifex.
You need do it there.

**Comment by rbuj** [comment]
The manual of Atril is not available in transifex.

**Comment by raveit65** [comment]
Really...,
thanks for pointing that out , i will add the manual to transifex.

**Comment by raveit65** [comment]
@rbuj 
I just added master--atril-user-quide and 1.20--atril-user-quide to transifex.
You can start with translations.
`tx pull -a -f` works fine for me.

**Comment by rbuj** [comment]
Thanks. I sent the Catalan translation using:
$ tx push -l ca --translations --resource MATE.master--atril-user-quide

**Comment by raveit65** [comment]
Nice, you can push a already translated .po file with tx-client to transifex?
... i didn't know that :)

**Pull request closed without merging**
