### PR TITLE
deprecations

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
You can create a pdf with libreoffice with a password.
The message area you see if you don't file out a password if reguested during opening a document..

**Comment by monsta** [comment]
I'm not sure why toolbar editor has a horizontal separator inside its window, but that separator is vertically expanded on window resize, which doesn't look very good...

Default window size:
atril-1

Resized window:
atril-2

**Comment by monsta** [comment]
Other stuff seems to be ok, including the password dialog.

**Comment by raveit65** [comment]
For some reason this does not happen with submarine themes, which i use mostly.
But, confirmed.....

**Comment by raveit65** [comment]
@monsta 
Separator is fixed.

**Comment by monsta** [comment]
Who could've thought you can expand separator in the unusual direction :slightly_smiling_face:

**Comment by raveit65** [comment]
It was simply a copy&paste typo, it was never expand vertical with GtkAlignment.
```
-          alignment = gtk_alignment_new (0.5, 0.5, 1.0, 0.0);
```
But yes, the separator is a bit weird. In css i can set a background, border, and vertical/horizontal size.
For this reason i didn't saw the issue with submarine themes as here was only the border defined. :slightly_smiling_face:

**Pull request merged**
