### PR TITLE
migrate to python3 for test cases

### PR DESCRIPTION
**Pull request by yetist**
May be it is the last part of mate-desktop is not working with python3.

This changes need to run with dogtail, it's a GUI test tool and automation framework, It is based on accessibility and I think it's amazing.

Please use the last release version of dogtail: https://gitlab.com/dogtail/dogtail/-/tags/DOGTAIL_0_9_11

Please configure with:
```
./configure --enable-tests
```
Run test use:
```
make check
```

### CODE REVIEW

**Comment by yetist** [comment]
The effect of GUI automatic testing.

record-atril

**Comment by raveit65** [comment]
This is funny :)
`make check` gives me a lot of opening windows with dogtail.
It seems to be working.
Beside from that all checks failed here .
```
make  check-TESTS
make[2]: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/atril-dist/test'
make[3]: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/atril-dist/test'
FAIL: test1.py
FAIL: test2.py
FAIL: test3.py
FAIL: test4.py

(atril:28596): AtrilDocument-CRITICAL **: 16:39:20.617: ev_document_get_n_pages: assertion 'EV_IS_DOCUMENT (document)' failed

(atril:28596): AtrilDocument-CRITICAL **: 16:39:20.617: ev_document_get_n_pages: assertion 'EV_IS_DOCUMENT (document)' failed

(atril:28596): AtrilDocument-CRITICAL **: 16:39:20.617: ev_document_has_text_page_labels: assertion 'EV_IS_DOCUMENT (document)' failed
FAIL: test5.py
============================================================================
Testsuite summary for atril 1.23.0
============================================================================
# TOTAL: 5
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  5
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to https://mate-desktop.org/
============================================================================
make[3]: *** [Makefile:656: test-suite.log] Error 1
make[3]: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/atril-dist/test'
make[2]: *** [Makefile:764: check-TESTS] Error 2
make[2]: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/atril-dist/test'
make[1]: *** [Makefile:866: check-am] Error 2
make[1]: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/atril-dist/test'
make: *** [Makefile:669: check-recursive] Error 1
```

**Comment by yetist** [comment]
The dogtail maybe not stable enough, logout and login may be helpful before test it again.

This is a full record of `make check`, and they all passed.
Peek 2019-06-25 23-31

**Comment by raveit65** [comment]
Do you interact by with the mouse in the opened windows?
Here it goes to fast on my box and i don't have any chance to interact, and after 5 seconds i have only a lot of open atril windows.
I use this version of dogtail.
```
[rave@mother ~]$ rpm -qa *dogtail*
python3-dogtail-0.9.11-3.fc30.noarch
```
But my results shouldn't block this PR.

**Comment by yetist** [comment]
Please make sure before run the make check, there is no atril is running. And every test case will quit atrial at the end, so if there is a lot opened atril windows after test, that is not pass.

**Comment by yetist** [comment]
I dont know why, if Ihave time, I will test it on fedora 30.

**Comment by raveit65** [comment]
> Please make sure before run the make check, there is no atril is running.

Yes, atril wasn't running before

>  And every test case will quit atrial at the end, so if there is a lot opened atril windows after test, that is not pass.

This is exactly the result here, the atril windows don't close automatic, they still remains all open.

**Comment by yetist** [comment]
@raveit65 

Please test again on fedora 30, my test passwd on fedora 30.

**Comment by raveit65** [comment]
I have no idea to test this, btw. i got same result as before.
I can't interact with the windows because my disk system is too fast. (4 samsung 970pro, raid0, pciex lane splitting)
In 3 seconds i see only 7 open atril windows at my desktop and in terminal the test failed.
I would say ignore my results. We can merge it if it works for you.

**Comment by raveit65** [comment]
@vkareh @mate-desktop/core-team 
Maybe someone of you guys can test and review that?

**Comment by vkareh** [comment]
@yetist, I get the same experience as @raveit65. If I try to run `test1.py` manually I get the following:
```
Clicking on [menu | File]
Mouse button 1 click at (23.0,66.0)
Clicking on [menu item | Open…]
Traceback (most recent call last):
  File "./test/test1.py", line 18, in <module>
    click('Open…', roleName='menu item')
  File "/usr/local/lib/python3.7/dist-packages/dogtail/procedural.py", line 364, in __call__
    Click.node.click(button)
  File "/usr/local/lib/python3.7/dist-packages/dogtail/tree.py", line 466, in click
    rawinput.click(clickX, clickY, button)
  File "/usr/local/lib/python3.7/dist-packages/dogtail/rawinput.py", line 38, in click
    checkCoordinates(x, y)
  File "/usr/local/lib/python3.7/dist-packages/dogtail/rawinput.py", line 30, in checkCoordinates
    raise ValueError("Attempting to generate a mouse event at negative coordinates: (%s,%s)" % (x, y))
ValueError: Attempting to generate a mouse event at negative coordinates: (-2147483647.5,-2147483647.5)
```
wondering if this is related to HiDPI or multi-monitors or what...

**Pull request merged**
