### PR TITLE
update help

### PR DESCRIPTION
**Pull request by mbkma**
Test:
`$ yelp help/C`
This is mainly the help page of evince, with some adoptions to match Atrils UI. Originally I just wanted to add synctex help pages, but editing the index.docbook is a pain.
Screenshot at 2021-03-12 11-49-04

a new version of PR #518

### CODE REVIEW

**Comment by raveit65** [comment]
Something is wrong when executing help from menu or F1.
German
Bildschirmfoto zu 2021-03-14 17-21-18
English
Bildschirmfoto zu 2021-03-14 17-22-45

I created a new tarball from your branch with
`git submodule init && git submodule update --remote --recursive && autogen.sh && make && make distcheck`
and build a new RPM from the tarball.

**Comment by raveit65** [comment]
Ok `yelp help/C` works here.....

**Comment by raveit65** [comment]
It seems that nothing will be installed.
```
[rave@mother atril-dist]$ ls -l help/C
insgesamt 316
-rw-rw-r-- 1 rave rave  1641 14. Mär 16:44 annotation-properties.page
-rw-rw-r-- 1 rave rave  1365 14. Mär 16:44 annotations-delete.page
-rw-rw-r-- 1 rave rave   765 14. Mär 16:44 annotations-disabled.page
-rw-rw-r-- 1 rave rave   783 14. Mär 16:44 annotations-navigate.page
-rw-rw-r-- 1 rave rave  2170 14. Mär 16:44 annotations.page
-rw-rw-r-- 1 rave rave  1384 14. Mär 16:44 annotations-save.page
-rw-rw-r-- 1 rave rave  2620 14. Mär 16:44 bookmarks.page
-rw-rw-r-- 1 rave rave  1554 14. Mär 16:44 bug-filing.page
-rw-rw-r-- 1 rave rave  2117 14. Mär 16:44 commandline.page
-rw-rw-r-- 1 rave rave  2041 14. Mär 16:44 convertpdf.page
-rw-rw-r-- 1 rave rave  1672 14. Mär 16:44 convertPostScript.page
-rw-rw-r-- 1 rave rave  1510 14. Mär 16:44 convertSVG.page
-rw-rw-r-- 1 rave rave  1169 14. Mär 16:44 default-settings.page
-rw-rw-r-- 1 rave rave   857 14. Mär 16:44 develop.page
-rw-rw-r-- 1 rave rave   968 14. Mär 16:44 documentation.page
-rw-rw-r-- 1 rave rave  2640 14. Mär 16:44 duplex-10pages.page
-rw-rw-r-- 1 rave rave  2413 14. Mär 16:44 duplex-11pages.page
-rw-rw-r-- 1 rave rave  1357 14. Mär 16:44 duplex-12pages.page
-rw-rw-r-- 1 rave rave  3885 14. Mär 16:44 duplex-13pages.page
-rw-rw-r-- 1 rave rave  2651 14. Mär 16:44 duplex-14pages.page
-rw-rw-r-- 1 rave rave  1071 14. Mär 16:44 duplex-15pages.page
-rw-rw-r-- 1 rave rave  1435 14. Mär 16:44 duplex-16pages.page
-rw-rw-r-- 1 rave rave  1909 14. Mär 16:44 duplex-3pages.page
-rw-rw-r-- 1 rave rave  1389 14. Mär 16:44 duplex-4pages.page
-rw-rw-r-- 1 rave rave  3669 14. Mär 16:44 duplex-5pages.page
-rw-rw-r-- 1 rave rave  2658 14. Mär 16:44 duplex-6pages.page
-rw-rw-r-- 1 rave rave  2440 14. Mär 16:44 duplex-7pages.page
-rw-rw-r-- 1 rave rave  1387 14. Mär 16:44 duplex-8pages.page
-rw-rw-r-- 1 rave rave  3993 14. Mär 16:44 duplex-9pages.page
-rw-rw-r-- 1 rave rave  2081 14. Mär 16:44 duplex-npages.page
-rw-rw-r-- 1 rave rave  1004 14. Mär 16:44 editing.page
drwxrwxr-x 2 rave rave  4096 14. Mär 16:44 figures
-rw-rw-r-- 1 rave rave  2020 14. Mär 16:44 finding.page
-rw-rw-r-- 1 rave rave  1512 14. Mär 16:44 formats.page
-rw-rw-r-- 1 rave rave  1270 14. Mär 16:44 forms.page
-rw-rw-r-- 1 rave rave  2253 14. Mär 16:44 forms-saving.page
-rw-rw-r-- 1 rave rave 31416  8. Mär 15:06 index.docbook
-rw-rw-r-- 1 rave rave  1998 14. Mär 16:44 index.page
-rw-rw-r-- 1 rave rave   747 14. Mär 16:44 introduction.page
-rw-rw-r-- 1 rave rave  1052 14. Mär 16:44 invert-colors.page
-rw-rw-r-- 1 rave rave   297 14. Mär 16:44 legal-unported.xml
-rw-rw-r-- 1 rave rave   497 14. Mär 16:44 legal.xml
-rw-rw-r-- 1 rave rave  1842 14. Mär 16:44 license.page
-rw-rw-r-- 1 rave rave  5942 14. Mär 16:44 movingaround.page
-rw-rw-r-- 1 rave rave  2111 14. Mär 16:44 noprint.page
-rw-rw-r-- 1 rave rave   775 14. Mär 16:44 openerror.page
-rw-rw-r-- 1 rave rave  2346 14. Mär 16:44 opening.page
-rw-rw-r-- 1 rave rave  1493 14. Mär 16:44 password.page
-rw-rw-r-- 1 rave rave  2300 14. Mär 16:44 presentations.page
-rw-rw-r-- 1 rave rave  1157 14. Mär 16:44 print-2sided.page
-rw-rw-r-- 1 rave rave  1014 14. Mär 16:44 print-booklet.page
-rw-rw-r-- 1 rave rave  1855 14. Mär 16:44 print-differentsize.page
-rw-rw-r-- 1 rave rave  1445 14. Mär 16:44 printing.page
-rw-rw-r-- 1 rave rave   742 14. Mär 16:44 print-order.page
-rw-rw-r-- 1 rave rave  1797 14. Mär 16:44 print-pagescaling.page
-rw-rw-r-- 1 rave rave   714 14. Mär 16:44 print-select.page
-rw-rw-r-- 1 rave rave   933 14. Mär 16:44 reload.page
-rw-rw-r-- 1 rave rave  2538 14. Mär 16:44 singlesided-13-16pages.page
-rw-rw-r-- 1 rave rave  2549 14. Mär 16:44 singlesided-17-20pages.page
-rw-rw-r-- 1 rave rave  2449 14. Mär 16:44 singlesided-3-4pages.page
-rw-rw-r-- 1 rave rave  2502 14. Mär 16:44 singlesided-5-8pages.page
-rw-rw-r-- 1 rave rave  2526 14. Mär 16:44 singlesided-9-12pages.page
-rw-rw-r-- 1 rave rave  2742 14. Mär 16:44 singlesided-npages.page
-rw-rw-r-- 1 rave rave  1908 14. Mär 16:44 synctex-beamer.page
-rw-rw-r-- 1 rave rave   951 14. Mär 16:44 synctex-compile.page
-rw-rw-r-- 1 rave rave  1716 14. Mär 16:44 synctex-editors.page
-rw-rw-r-- 1 rave rave   662 14. Mär 16:44 synctex.page
-rw-rw-r-- 1 rave rave  2384 14. Mär 16:44 synctex-search.page
-rw-rw-r-- 1 rave rave  1289 14. Mär 16:44 synctex-support.page
-rw-rw-r-- 1 rave rave  1331 14. Mär 16:44 textselection.page
-rw-rw-r-- 1 rave rave  1177 14. Mär 16:44 translate.page
```
But an installation to /usr/local/ doesn't show anything.
```
[rave@mother atril-dist]$ ls -l /usr/local/share/help/C/atril/
insgesamt 12
drwxr-xr-x 2 root root 4096 14. Mär 17:43 figures
-rw-r--r-- 1 root root 1998 14. Mär 17:43 index.page
-rw-r--r-- 1 root root  497 14. Mär 17:43 legal.xml
```

**Comment by mbkma** [comment]
@raveit65 should be fixed now.

**Review by raveit65 — APPROVED** [review]
This works fine now,
thanks.

**Pull request merged**
