### PR TITLE
thumbnailer: Fix memory leak

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by sc0w** [comment]
New warnings in the logs detected:

```
atril-thumbnailer.c:231:16: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  231 |    g_strfreev (file_arguments);
      |                ^~~~~~~~~~~~~~
      |                |
      |                const gchar ** {aka const char **}

atril-thumbnailer.c:236:47: warning: passing argument 1 of 'g_strv_length' from incompatible pointer type [-Wincompatible-pointer-types]
  236 |  if (file_arguments == NULL || g_strv_length (file_arguments) != 2) {
      |                                               ^~~~~~~~~~~~~~
      |                                               |
      |                                               const gchar ** {aka const char **}

atril-thumbnailer.c:240:16: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  240 |    g_strfreev (file_arguments);
      |                ^~~~~~~~~~~~~~
      |                |
      |                const gchar ** {aka const char **}

atril-thumbnailer.c:249:15: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  249 |   g_strfreev (file_arguments);
      |               ^~~~~~~~~~~~~~
      |               |
      |               const gchar ** {aka const char **}

atril-thumbnailer.c:258:15: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  258 |   g_strfreev (file_arguments);
      |               ^~~~~~~~~~~~~~
      |               |
      |               const gchar ** {aka const char **}

atril-thumbnailer.c:268:15: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  268 |   g_strfreev (file_arguments);
      |               ^~~~~~~~~~~~~~
      |               |
      |               const gchar ** {aka const char **}

atril-thumbnailer.c:276:15: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  276 |   g_strfreev (file_arguments);
      |               ^~~~~~~~~~~~~~
      |               |
      |               const gchar ** {aka const char **}

atril-thumbnailer.c:301:15: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  301 |   g_strfreev (file_arguments);
      |               ^~~~~~~~~~~~~~
      |               |
      |               const gchar ** {aka const char **}

atril-thumbnailer.c:309:15: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  309 |   g_strfreev (file_arguments);
      |               ^~~~~~~~~~~~~~
      |               |
      |               const gchar ** {aka const char **}

atril-thumbnailer.c:317:14: warning: passing argument 1 of 'g_strfreev' from incompatible pointer type [-Wincompatible-pointer-types]
  317 |  g_strfreev (file_arguments);
      |              ^~~~~~~~~~~~~~
      |              |
      |              const gchar ** {aka const char **}
```

**Comment by rbuj** [comment]
@sc0w done

**Comment by raveit65** [comment]
@sc0w 
Does this works for you?

**Comment by sc0w** [comment]
@rbuj 

why do you think there is memory leak without this PR?

I think const variables don't need to be freed

**Comment by rbuj** [comment]
@sc0w 

> G_OPTION_ARG_STRING_ARRAY or G_OPTION_ARG_FILENAME_ARRAY, the data should be freed using g_strfreev().

REF: https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html

**Pull request merged**
