### PR TITLE
Don't crash on a truncated pdf

### PR DESCRIPTION
**Pull request by raveit65**
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1536856
Reporter already confirmed that this backports fixes the issue.
Please test.
A truncated pdf can be downloaded at rhbz report.

### CODE REVIEW

**Comment by raveit65** [comment]
Well, most commits are from other PR.....
Those fixes the issue.
 - Use GtkOverlay to show the loading message
- libview: Check number of pages on ev_view_document_changed_cb
- libview: Add check for pageless documents to ev_view_accessible_focus…

**Comment by raveit65** [comment]
Gdb shows me that atril crashes with
```
Thread 1 "atril" received signal SIGSEGV, Segmentation fault.
ev_view_accessible_selection_changed (view=0x555555db2280 [EvView], 
    view_accessible=<optimized out>) at ev-view-accessible.c:351
351		g_signal_emit_by_name (page_accessible, "text-selection-changed");
```
now. Fix coming soon. Please test again.

**Comment by lukefromdc** [comment]
Holding on testing this until the next fix is added to it

**Comment by raveit65** [comment]
No, this is fixed now.
- libview: Check number of pages when processing button events

is for latest crash.

**Pull request merged**
