### PR TITLE
deprecation fixes and backports from evince

### PR DESCRIPTION
**Pull request by raveit65**
I stopped here to fix more because the PR is huge enough.
@monsta @flexiondotorg @XRevan86 @lukefromdc
Please review

### CODE REVIEW

**Comment by monsta** [comment]
Oh, it's large indeed. I'll check it a bit later.

**Comment by lukefromdc** [comment]
I just tested dev-deprecations2, it seemed to work fine for me using GTK 3.21 master

**Comment by monsta** [comment]
Well, seems to work fine here in GTK+2 build.

**Comment by monsta** [comment]
Seems to work same as before in GTK+ 3.20 too.

**Pull request merged**
