### PR TITLE
Basicly improvements (back ports) for a11y and caret navigation

### PR DESCRIPTION
**Pull request by raveit65**
This is the state of ATK in evince-3.12.x.
Not sure if more back ports are needed from upstream, but this needs to be tested first and we need time for translators for all changes in 1.19 development before 1.20.

Please Test.

### CODE REVIEW

**Comment by raveit65** [comment]
@alexarnaud
Feel free to test this too....

**Comment by Butterfly** [comment]
Hi.. Thank you for caring about accessibility!

Saw your shout out on Debian-Accessibility and forwarded it to Debian-User. Vinux is next if they don't forward from Orca in the next couple hours.

Am now poking my nose in to ask: What kind of things are you looking for? Am asking on behalf of users without visual impairments who still might want to try and help.

For this very second, I've just installed a stable copy via apt-get on a newly debootstrap'ed Debian Stretch. Beyond your visual impairment focus, it's very clean and simple which also makes it very *cognitively friendly*, another great accessibility/usability plus from my personal set of Life Shoes. :smile:

**Comment by alexarnaud** [comment]
@Butterfly you need to compile Atril from source and install it on the target computer.

What we need to check is : does Atril provide the same degree of accessibility than Evince ?

Best regards.

**Comment by raveit65** [comment]
Simply build from 1.19.5 released tarball
http://pub.mate-desktop.org/releases/1.19/atril-1.19.5.tar.xz
Atril supports now caret-navigation with this release, enable it with F7.
Means, you can navigate through the document with the keyboard.
Than you were able to hear orca speaking every word or sentence in a pdf document.

**Comment by Butterfly** [comment]
Thank you, Alex, that was a fast turn-around! I just searched my email inbox for any mention of Evince before I attempt compiling Atril. Only found 30 references at all in ~200,000 emails.

For now, the only thing that stood out in my inbox without testing anything yet was that Evince at some point had a problem displaying some international languages that Linux users might speak. I don't know if that was ever corrected, but it still sounded important enough to mention out loud as a notable benchmark.

Something else that seemed notable was where another Debian user observed that Evince would sometimes have trouble displaying "PDFs generated by applications which are not primarily PDF creators." I couldn't immediately find any further details as to what didn't display well nor what might have originally generated the problem document. Figured it wouldn't hurt to mention that point, either, since those of you who are deeply involved in this subject matter might have a better idea of what could have led to that user's experience.

I'm off to try to compile. That's always a huge challenge in and of itself, grin. Thank you again for caring! :smile:

**Comment by alexarnaud** [comment]
Le 13/12/2017 à 19:18, raveit65 a écrit :
> Simply build from 1.19.5 released tarball
> http://pub.mate-desktop.org/releases/1.19/atril-1.19.5.tar.xz
> Atril supports now caret-navigation with this release, enable it with F7.
> Means, you can navigate through the document with the keyboard.
> Than you were able to hear orca speaking every word or sentence in a pdf 
> document.

On Debian Sid with Orca enabled, when I try to open a PDF I obtain this 
error:

> (atril:32064): GLib-GObject-WARNING **: ../../../../gobject/gsignal.c:2423: signal 'annot-removed' is invalid for instance '0x563c1159ba30' of type 'EvView'
> 
> (atril:32064): GLib-GObject-WARNING **: ../../../../gobject/gsignal.c:2423: signal 'cursor-moved' is invalid for instance '0x563c1159ba30' of type 'EvView'
> 
> (atril:32064): Gdk-CRITICAL **: gdk_screen_get_monitor_scale_factor: assertion 'monitor_num < gdk_screen_get_n_monitors (screen)' failed
> atril: symbol lookup error: atril: undefined symbol: ev_view_supports_caret_navigation

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
I don't get this warnings here with fedora 26 and orca reads the document if i enabled carret-navigaion with pressing F7.

**Comment by raveit65** [comment]
Tested wih new releases 1.19.6

**Comment by monsta** [comment]
I can reproduce the shift+click issue (fixed by https://github.com/mate-desktop/atril/commit/e6672a875c89cfd81d4e54ae8b1a8a834eb6fe8b) in 1.18, I think it's worth cherry-picking. All other commits seem to be useful only for master or 1.20, if I haven't missed anything.

**Comment by monsta** [comment]
Ah dammit, `extend_selection_from_cursor` isn't in 1.18... :confused:

**Comment by raveit65** [comment]
@alexarnaud 
Don't know if your problems with orc still exists, maybe this helps.
Please test.
https://github.com/mate-desktop/atril/pull/311

**Comment by alexarnaud** [comment]
Le 02/04/2018 à 17:42, raveit65 a écrit :
> @alexarnaud <https://github.com/alexarnaud>
> Don't know if your problems with orc still exists, maybe this helps.
> Please test.
> #311 <https://github.com/mate-desktop/atril/pull/311>

I don't reproduce issue when starting Atril with Orca open. I'll try to 
test #311.

Best regards,
Alex.

**Comment by monsta** [comment]
Ok, managed to port shift+click fix to 1.18 in https://github.com/mate-desktop/atril/commit/3b64a164663d53e1c348eae76a1be7285c560588.

**Pull request merged**
