### PR TITLE
Added accelerator 't' for toggling visibility of the toolbar.

### PR DESCRIPTION
**Pull request by apalsson**
This adds an accelerator to toggle the toolbar just like the side panel.
"T" was chosen as an accelerator as it is not used by any other action and it also fits with the action target's name.

### CODE REVIEW

**Comment by vkareh** [comment]
@mate-desktop/core-team - is this something we're interested in? Seems like a reasonable addition, considering we already have single letter accelerator for many View settings in Atril

**Comment by alexarnaud** [comment]
> @mate-desktop/core-team - is this something we're interested in? Seems like a reasonable addition, considering we already have single letter accelerator for many View settings in Atril

A question, what's happening if a user try to write the letter "T" inside a PDF form?

Best regards.

**Comment by apalsson** [comment]
> A question, what's happening if a user try to write the letter "T" inside a PDF form?
> 
Nothing, focus on a edit widget inside a document disables accelerators.

**Comment by alexarnaud** [comment]
Le 11/09/2019 à 08:04, A. Palsson a écrit :
> Nothing, focus on a edit widget inside a document disables accelerators.
> 

OK, thanks for the clarification.

Best regards.

**Pull request merged**
