### PR TITLE
Use GLib's new g_clear_signal_handler() function to simplify code

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj
Can you please push PR to get a deployment?

**Comment by rbuj** [comment]
done

**Review by lukefromdc — APPROVED** [review]
I only use a limited set of features with atril and the PDF documents I have so could not test everything (notably could not test annotations) but in basic interaction witn PDFs behavior seems to be the same as in master. Zoom control (affected by this) works fine with no new issues on my end

**Comment by raveit65** [comment]
@rbuj 
Deployment is missing.

**Comment by raveit65** [comment]
In a quick test it seems ok, i'd like to test it a few days more.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
