### PR TITLE
ev-window: expand the comment on about dialog

### PR DESCRIPTION
**Pull request by rbuj**
### Before

Screenshot at 2020-03-31 17-45-47

### After

Screenshot at 2020-03-31 18-07-47

### CODE REVIEW

**Comment by rbuj** [comment]
The comment is pulled from https://mate-desktop.org/

**Comment by sc0w** [comment]
I prefer the little dialog as before

**Comment by rbuj** [comment]
@sc0w following the general directions of gtk https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html#GtkAboutDialog--comments

Screenshot at 2020-03-31 20-48-04

or

Screenshot at 2020-03-31 20-58-00

**Comment by sc0w** [comment]
```
Atril

1.24.0

Atril is ...
Atril is ...
```

atril isn't needed to mention it in the comments

and again, I dont like the full stop next to the number version of synctex

**Comment by rbuj** [comment]
@selectiveduplicate
- Atril allows you to edit tex files in Pluma and view the output in Atril using SyncTex 1.21 and poppler/cairo 0.84.0.

**Comment by sc0w** [comment]
> Atril allows you to edit tex files in Pluma and view the output in Atril using SyncTex 1.21 and poppler/cairo 0.84.0.

The full stop in number version looks weird for me.

and... atril isn't a document viewer? it only can `edit tex files in Pluma and view the output in Atril`?

**Comment by rbuj** [comment]
It removes a feasible confusion of what applications do.

Screenshot at 2020-04-01 18-48-26

**Comment by raveit65** [comment]
Talking about pluma here sounds a bit weird, because people can use another editor, eg. geany, vim etc.
So my favourite is a edit of
Screenshot at 2020-03-31 20-58-00
```
Atril is a simple multi-page document viewer,
powered by poppler/cairo 0.84.0 and SyncTEX 1.21.
```
I don't care if there is a dot or not after SyncTex version.

**Comment by rbuj** [comment]
@raveit65 done.

Screenshot at 2020-04-13 22-52-50

**Pull request merged**
