### PR TITLE
support webkit2gtk-4.1and 4.0

### PR DESCRIPTION
**Pull request by raveit65**
- fixes https://github.com/mate-desktop/atril/issues/582

### CODE REVIEW

**Review by zhuyaliang — APPROVED** [review]
Agree to merge

**Review by vkareh — APPROVED** [review]
This works and fixes the libsoup conflicts when opening epub files in F38

**Comment by raveit65** [comment]
@vkareh 
I didn't know about libsoup issue in f38. Can you please open an rhbz?
I don't want to forget to update fedora.

**Comment by raveit65** [comment]
@vkareh 
So this 5 days old version has this issue?
https://bodhi.fedoraproject.org/updates/FEDORA-2023-2fc666d008

**Comment by vkareh** [comment]
@raveit65 I just compiled from `master` and tried opening an epub. Got this error:
```
(atril:141091): libsoup-ERROR **: 10:51:05.288: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
```
And Atril crashed without opening the file.

**Comment by raveit65** [comment]
Just update CI to build with webkit2-4.1

**Comment by raveit65** [comment]
> @raveit65 I just compiled from `master` and tried opening an epub. Got this error:
> 
> ```
> (atril:141091): libsoup-ERROR **: 10:51:05.288: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
> ```
> 
> And Atril crashed without opening the file.

Ok, i will cherry pick that to 1.26 branch
and update fedora f37+

**Comment by vkareh** [comment]
>  Btw. what -devel package is installed in your box?

```
$ dnf info --installed  webkit2gtk4\*devel | grep ^Name
Name         : webkit2gtk4.0-devel
Name         : webkit2gtk4.1-devel
```
They are both sourced from the same `webkitgtk-2.40.1-1.fc38.src.rpm`

**Comment by raveit65** [comment]
Maybe remove one -devel source?
Because i can't reproduce your issue with fedora official 1.26.1 rpm which was build against old obsolete  webkit2gtk3-devel.
Also i don't see this issue with my local 1.7.0 build which use webkit2gtk4.0-devel as source.

**Pull request merged**
