### PR TITLE
Render documents correctly on HiDPI displays

### LINKED ISSUE #296: HiDPI Rendering Scale
#### Expected behaviour

Atril should render documents to fit their page size with `window-scaling-factor>1`.

#### Actual behaviour

Atril renders the contents of each page of any document at a scale factor of 1, while the page itself is rendered at the correct scale.

#### Steps to reproduce the behaviour

1. Set `window-scaling-factor=2`.
2. Open a PDF to observe the discrepancy.

#### MATE general version

1.20

#### Package version

`master` from git.

#### Linux Distribution

Gentoo Linux

#### Screenshot

screenshot at 2018-02-28 08-26-25

### PR DESCRIPTION
**Pull request by vkareh**
* https://git.gnome.org/browse/evince/commit/?id=a612f8
* https://git.gnome.org/browse/evince/commit/?id=90a258
* https://git.gnome.org/browse/evince/commit/?id=37c13b

Fixes #296

### CODE REVIEW

**Comment by raveit65** [comment]
This pulls in a deprecation warning.
```
ev-view-presentation.c: In function 'ev_view_presentation_update_monitor_geometry':
ev-view-presentation.c:1241:2: warning: 'gdk_screen_get_monitor_at_window' is deprecated: Use 'gdk_display_get_monitor_at_window' instead [-Wdeprecated-declarations]
  monitor_num = gdk_screen_get_monitor_at_window (screen, gtk_widget_get_window (GTK_WIDGET (pview)));
  ^~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31:0,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ev-view-presentation.c:25:
/usr/include/gtk-3.0/gdk/gdkscreen.h:91:15: note: declared here
 gint          gdk_screen_get_monitor_at_window (GdkScreen *screen,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ev-view-presentation.c:1242:2: warning: 'gdk_screen_get_monitor_geometry' is deprecated: Use 'gdk_monitor_get_geometry' instead [-Wdeprecated-declarations]
  gdk_screen_get_monitor_geometry (screen, monitor_num, &monitor);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31:0,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ev-view-presentation.c:25:
/usr/include/gtk-3.0/gdk/gdkscreen.h:78:14: note: declared here
 void         gdk_screen_get_monitor_geometry  (GdkScreen    *screen,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Which was already fixed here https://github.com/mate-desktop/atril/commit/0568785bbd484714a63caa4b9ca9639a2867d6e9
Commit looks like we can fix the deprecation again?

**Comment by raveit65** [comment]
@flexiondotorg 
Can you test the presentation mode (F5) too?

**Comment by flexiondotorg** [comment]
@raveit65 Presentation mode looks good to me.

**Comment by raveit65** [comment]
I fixed the deprecation, i hope i did not break anything...
@vkareh @flexiondotorg 
Can you test the presentation mode again with your HIDPI monitors on bare metal please?
In qemu VM with non-hidipi monitor this mode looks broken with or without my deprecation fix, it has blurred fonts and images.
Tested with https://www.nasa.gov/sites/default/files/atoms/files/jsc_benefits_for_humanity_tagged_6-30-15.pdf
But i am not sure if this can be tested in VM.

**Comment by flexiondotorg** [comment]
@raveit65 Presentation mode works with the recent update to this pull request.

**Pull request merged**
