### PR TITLE
synctex update

### PR DESCRIPTION
**Pull request by raveit65**
@monsta @flexiondotorg 
Please review

### CODE REVIEW

**Comment by monsta** [comment]
Well, I planned to switch to distro-packaged synctex for 1.16... just need to check if all the distros have it packaged.

**Comment by raveit65** [comment]
Huh, that pulls in a lot of dependencies
```
Installing:
 texlive-synctex     noarch 5:svn37078.0-24.fc24.1                 fedora  31 k
Installing for dependencies:
 perl-XML-XPath      noarch 1.36-1.fc24                            fedora  86 k
 texlive-base        noarch 5:2015-24.20150728_r37987.fc24         fedora 1.6 M
 texlive-hyphen-base noarch 5:svn34525.0-24.fc24.1                 fedora  51 k
 texlive-kpathsea    noarch 5:svn37193.0-24.fc24.1                 fedora 153 k
 texlive-kpathsea-bin
                     x86_64 5:svn37207.0-24.20150728_r37987.fc24.1 fedora  52 k
 texlive-metafont    noarch 5:svn37078.2.7182818-24.fc24.1         fedora  71 k
 texlive-metafont-bin
                     x86_64 5:svn36790.0-24.20150728_r37987.fc24.1 fedora 216 k
 texlive-synctex-bin x86_64 5:svn36790.0-24.20150728_r37987.fc24.1 fedora  39 k
 texlive-tetex       noarch 5:svn38208.3.0-24.fc24.1               fedora 113 k
 texlive-tetex-bin   noarch 5:svn36770.0-24.20150728_r37987.fc24.1 fedora  30 k
 texlive-texlive.infra
                     noarch 5:svn37738.0-24.fc24.1                 fedora 155 k
 texlive-texlive.infra-bin
                     x86_64 5:svn36790.0-24.20150728_r37987.fc24.1 fedora  28 k

Transaction Summary
================================================================================
Install  1 Package (+12 Dependent packages)
```
+ the tons of mathjax packages.

**Comment by monsta** [comment]
I'm kind of confused by "noarch" there... because what we need is a shared library (see [here](https://packages.debian.org/stretch/amd64/libsynctex1/filelist)), so it should be marked as x86_64.
In Debian this package depends only on libc6 and zlib1g.

**Comment by raveit65** [comment]
It is in
```
5:texlive-lib-2015-24.20150728_r37987.fc24.x86_64 : Shared libraries for TeX-related
                                                  : files
Repo        : fedora
Matched from:
Filename    : /usr/lib64/libsynctex.so.1
Filename    : /usr/lib64/libsynctex.so.1.18.0
```
which i already use for dvi backend
```
# for the dvi back-end
%if 0%{?fedora} >= 24
BuildRequires:  texlive-lib-devel
%else
BuildRequires:  texlive-kpathsea-lib-devel
%endif
```
But isn't it worse to use this PR for the moment?
.....work is already done.

**Comment by monsta** [comment]
Well... I don't mind, I can postpone the migration to 1.18.

**Comment by monsta** [comment]
So far, all is fine in GTK+2 build here.

**Comment by raveit65** [comment]
Ok, thanks for testing

**Comment by raveit65** [comment]
Btw, we can use it for 1.14.x if your work is 1.16 only.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/atril/commit/4e2cf26a825b5c8d30f6a84227a1f4d279928859
https://github.com/mate-desktop/atril/commit/b307e10130b239f092905ac42028f499df74aa9b
https://github.com/mate-desktop/atril/commit/300f71eb205a43609ddfceefce08559e09e9f7f3
https://github.com/mate-desktop/atril/commit/9edc6719f9b98ccc19cc78521af5f53cdc05d3cb
https://github.com/mate-desktop/atril/commit/ba8d0f79a864b445ea0374a7dc5f9d9af7687859

**Comment by monsta** [comment]
Let's use it for 1.16 only - it's quite a big change. I might overlook something during testing, and I don't have all types of documents here :smile:

**Pull request closed without merging**
